export const webDevelopmentSkills = [
  { id: "html", label: "HTML5" },
  { id: "css", label: "CSS3" },
  { id: "javascript", label: "JavaScript (ES6+)" },
  { id: "typescript", label: "TypeScript" },
  { id: "react", label: "React.js" },
  { id: "nextjs", label: "Next.js" },
  { id: "vue", label: "Vue.js" },
  { id: "nuxt", label: "Nuxt.js" },
  { id: "angular", label: "Angular" },
  { id: "svelte", label: "Svelte" },
  { id: "nodejs", label: "Node.js" },
  { id: "express", label: "Express.js" },
  { id: "nestjs", label: "NestJS" },
  { id: "tailwind", label: "Tailwind CSS" },
  { id: "sass", label: "SASS / SCSS" },
  { id: "bootstrap", label: "Bootstrap" },
  { id: "mongodb", label: "MongoDB" },
  { id: "postgresql", label: "PostgreSQL" },
  { id: "mysql", label: "MySQL" },
  { id: "prisma", label: "Prisma ORM" },
  { id: "graphql", label: "GraphQL" },
  { id: "rest_api", label: "RESTful APIs" },
  { id: "firebase", label: "Firebase" },
  { id: "supabase", label: "Supabase" },
  { id: "docker", label: "Docker" },
  { id: "aws", label: "AWS" },
  { id: "vercel", label: "Vercel" },
  { id: "git", label: "Git & GitHub" },
  { id: "ci_cd", label: "CI/CD Pipelines" },
  { id: "pwa", label: "Progressive Web Apps (PWA)" },
  { id: "web_security", label: "Web Security & OAuth" },
];

export const appDevelopmentSkills = [
  { id: "react_native", label: "React Native" },
  { id: "flutter", label: "Flutter" },
  { id: "dart", label: "Dart" },
  { id: "swift", label: "Swift" },
  { id: "swiftui", label: "SwiftUI" },
  { id: "kotlin", label: "Kotlin" },
  { id: "java", label: "Java (Android)" },
  { id: "jetpack_compose", label: "Jetpack Compose" },
  { id: "objective_c", label: "Objective-C" },
  { id: "android_sdk", label: "Android SDK" },
  { id: "ios_sdk", label: "iOS SDK" },
  { id: "xcode", label: "Xcode" },
  { id: "android_studio", label: "Android Studio" },
  { id: "expo", label: "Expo" },
  { id: "firebase", label: "Firebase Cloud Messaging" },
  { id: "sqlite", label: "SQLite / Room DB" },
  { id: "realm", label: "Realm Database" },
  { id: "app_store_deploy", label: "App Store Deployment" },
  { id: "play_store_deploy", label: "Google Play Deployment" },
  { id: "graphql", label: "GraphQL Mobile" },
  { id: "rest_api", label: "REST APIs Integration" },
  { id: "push_notifications", label: "Push Notifications" },
  { id: "in_app_purchases", label: "In-App Purchases (IAP)" },
  { id: "bluetooth_ble", label: "Bluetooth / BLE" },
  { id: "geolocation_maps", label: "Geolocation & Maps" },
  { id: "mobile_ui_ux", label: "Mobile UI/UX Design" },
  { id: "offline_sync", label: "Offline First Sync" },
  { id: "ci_cd_mobile", label: "Fastlane & Mobile CI/CD" },
];

export const graphicDesignSkills = [
  { id: "photoshop", label: "Adobe Photoshop" },
  { id: "illustrator", label: "Adobe Illustrator" },
  { id: "figma", label: "Figma" },
  { id: "indesign", label: "Adobe InDesign" },
  { id: "xd", label: "Adobe XD" },
  { id: "sketch", label: "Sketch" },
  { id: "after_effects", label: "Adobe After Effects" },
  { id: "canva", label: "Canva Pro" },
  { id: "coreldraw", label: "CorelDRAW" },
  { id: "blender", label: "Blender 3D" },
  { id: "cinema_4d", label: "Cinema 4D" },
  { id: "procreate", label: "Procreate" },
  { id: "logo_design", label: "Logo & Brand Identity" },
  { id: "brand_guidelines", label: "Brand Style Guides" },
  { id: "ui_design", label: "UI (User Interface) Design" },
  { id: "ux_research", label: "UX Research & Wireframing" },
  { id: "design_systems", label: "Design Systems & Component Libraries" },
  { id: "typography", label: "Typography & Font Pairing" },
  { id: "packaging_design", label: "Packaging & Label Design" },
  { id: "vector_illustration", label: "Vector Illustration" },
  { id: "banner_ads", label: "Ad Creatives & Banner Design" },
  { id: "social_media_graphics", label: "Social Media Post Design" },
  { id: "print_design", label: "Print Production & CMYK" },
  { id: "infographics", label: "Infographic Design" },
  { id: "iconography", label: "Icon Set Design" },
  { id: "photo_retouching", label: "Photo Retouching & Color Correction" },
  { id: "3d_modeling", label: "3D Product Visualization" },
];

export const consultingStrategySkills = [
  { id: "strategic_planning", label: "Strategic Planning" },
  { id: "business_analysis", label: "Business Analysis" },
  { id: "market_research", label: "Market Research & Sizing" },
  { id: "competitor_analysis", label: "Competitor Analysis" },
  { id: "financial_modeling", label: "Financial Modeling & Valuation" },
  { id: "business_plan", label: "Business Plan Writing" },
  { id: "pitch_deck", label: "Investor Pitch Deck Preparation" },
  { id: "project_management", label: "Agile Project Management" },
  { id: "risk_management", label: "Risk Management & Compliance" },
  { id: "change_management", label: "Change Management" },
  { id: "operations_optimization", label: "Operations Optimization" },
  { id: "growth_strategy", label: "Go-to-Market (GTM) Strategy" },
  { id: "kpi_metrics", label: "KPIs & Performance Dashboards" },
  { id: "product_management", label: "Product Management" },
  { id: "customer_journey", label: "Customer Journey Mapping" },
  { id: "supply_chain", label: "Supply Chain Strategy" },
  { id: "digital_transformation", label: "Digital Transformation" },
  { id: "m_and_a", label: "M&A Due Diligence" },
  { id: "pricing_strategy", label: "Pricing & Monetization Strategy" },
  { id: "leadership_coaching", label: "Executive Leadership Coaching" },
  { id: "crm_strategy", label: "CRM & Sales Pipeline Strategy" },
  { id: "data_driven_insights", label: "Data-Driven Business Intelligence" },
  { id: "stakeholder_management", label: "Stakeholder Management" },
  { id: "swot_analysis", label: "SWOT & PESTLE Analysis" },
  { id: "hr_organizational_design", label: "Organizational Design & HR Strategy" },
];

export const contentWritingSkills = [
  { id: "copywriting", label: "Copywriting" },
  { id: "seo_writing", label: "SEO Content Writing" },
  { id: "blog_writing", label: "Blog & Article Writing" },
  { id: "technical_writing", label: "Technical Writing & Documentation" },
  { id: "creative_writing", label: "Creative Writing" },
  { id: "content_strategy", label: "Content Strategy & Planning" },
  { id: "email_copywriting", label: "Email Marketing Copy" },
  { id: "landing_page_copy", label: "Landing Page Copywriting" },
  { id: "social_media_copy", label: "Social Media Captions & Copy" },
  { id: "press_releases", label: "Press Release Writing" },
  { id: "ghostwriting", label: "Ghostwriting (Books & Thought Leadership)" },
  { id: "whitepapers", label: "Whitepapers & E-books" },
  { id: "case_studies", label: "Case Study Writing" },
  { id: "scriptwriting", label: "Video & Podcast Scriptwriting" },
  { id: "proofreading", label: "Proofreading & Copyediting" },
  { id: "ux_writing", label: "UX Microcopy & App Content" },
  { id: "keyword_research", label: "Keyword Research & Optimization" },
  { id: "product_descriptions", label: "E-Commerce Product Descriptions" },
  { id: "storytelling", label: "Brand Storytelling" },
  { id: "academic_writing", label: "Academic & Research Writing" },
  { id: "newsletter_writing", label: "Substack & Newsletter Writing" },
  { id: "ad_copy", label: "Google & Meta Ad Copy" },
  { id: "translation", label: "Translation & Localization" },
  { id: "speechwriting", label: "Speechwriting" },
  { id: "brand_voice", label: "Brand Voice & Tone Guidelines" },
];

export const softwareDevelopmentSkills = [
  { id: "python", label: "Python" },
  { id: "javascript", label: "JavaScript" },
  { id: "typescript", label: "TypeScript" },
  { id: "java", label: "Java" },
  { id: "cplusplus", label: "C++" },
  { id: "csharp", label: "C#" },
  { id: "golang", label: "Golang" },
  { id: "rust", label: "Rust" },
  { id: "ruby", label: "Ruby & Ruby on Rails" },
  { id: "php", label: "PHP & Laravel" },
  { id: "sql", label: "SQL & Query Optimization" },
  { id: "nosql", label: "NoSQL (MongoDB, DynamoDB)" },
  { id: "redis", label: "Redis & In-Memory Caching" },
  { id: "docker", label: "Docker & Containerization" },
  { id: "kubernetes", label: "Kubernetes (K8s)" },
  { id: "microservices", label: "Microservices Architecture" },
  { id: "rest_apis", label: "REST & gRPC APIs" },
  { id: "graphql", label: "GraphQL" },
  { id: "aws_cloud", label: "AWS Cloud Architecture" },
  { id: "azure_cloud", label: "Microsoft Azure" },
  { id: "gcp", label: "Google Cloud Platform (GCP)" },
  { id: "ci_cd", label: "CI/CD & DevOps Automation" },
  { id: "git", label: "Git & Version Control" },
  { id: "unit_testing", label: "Unit & Integration Testing (Jest, PyTest)" },
  { id: "system_design", label: "High-Level System Design" },
  { id: "kafka", label: "Apache Kafka & Message Queues" },
  { id: "cybersecurity", label: "Application Security & Auth" },
];

export const videoProductionSkills = [
  { id: "premiere_pro", label: "Adobe Premiere Pro" },
  { id: "after_effects", label: "Adobe After Effects" },
  { id: "davinci_resolve", label: "DaVinci Resolve" },
  { id: "final_cut_pro", label: "Final Cut Pro" },
  { id: "color_grading", label: "Color Grading & Correction" },
  { id: "sound_design", label: "Sound Design & Audio Mixing" },
  { id: "motion_graphics", label: "Motion Graphics & 2D Animation" },
  { id: "3d_animation", label: "3D Animation (Blender/C4D)" },
  { id: "videography", label: "Cinematography & Camera Operation" },
  { id: "lighting", label: "Studio & Scene Lighting" },
  { id: "storyboarding", label: "Storyboarding & Script Breakdown" },
  { id: "drone_videography", label: "Drone / Aerial Videography" },
  { id: "video_editing", label: "Short-Form Video Editing (Reels/TikTok)" },
  { id: "youtube_editing", label: "YouTube Long-Form Video Editing" },
  { id: "green_screen", label: "Chroma Key & Green Screen" },
  { id: "subtitles_captions", label: "Subtitles & Dynamic Captions" },
  { id: "visual_effects", label: "VFX (Visual Effects)" },
  { id: "podcast_production", label: "Video Podcast Production" },
  { id: "live_streaming", label: "OBS & Live Streaming Setup" },
  { id: "voiceover", label: "Voiceover Recording & Sync" },
  { id: "promotional_videos", label: "Commercial & Promo Video Production" },
  { id: "explainer_videos", label: "SaaS Explainer Video Production" },
  { id: "music_licensing", label: "Audio Mastering & BGM Selection" },
  { id: "video_compression", label: "Encoding & Web Video Optimization" },
  { id: "directing", label: "Creative Directing & Production Management" },
];

export const socialMediaMarketingSkills = [
  { id: "social_strategy", label: "Social Media Strategy" },
  { id: "meta_ads", label: "Meta (Facebook & Instagram) Ads" },
  { id: "google_ads", label: "Google Search & Display Ads" },
  { id: "tiktok_ads", label: "TikTok Ads & Viral Strategy" },
  { id: "linkedin_marketing", label: "LinkedIn B2B Lead Generation" },
  { id: "content_calendar", label: "Content Calendar & Planning" },
  { id: "community_management", label: "Community Management & Engagement" },
  { id: "influencer_marketing", label: "Influencer Outreach & Partnerships" },
  { id: "analytics_reporting", label: "Social Media Analytics & Reporting" },
  { id: "copywriting_social", label: "Social Media Ad Copywriting" },
  { id: "short_form_content", label: "Reels / TikTok Content Creation" },
  { id: "canva_design", label: "Canva & Social Creative Design" },
  { id: "email_marketing", label: "Email Marketing & Automation (Klaviyo/Mailchimp)" },
  { id: "funnel_building", label: "Sales Funnel Optimization" },
  { id: "seo_basics", label: "Social SEO & Hashtag Optimization" },
  { id: "brand_growth", label: "Organic Audience Growth" },
  { id: "customer_retention", label: "Customer Retention & Loyalty Marketing" },
  { id: "buffer_hootsuite", label: "Scheduling Tools (Buffer, Hootsuite, Later)" },
  { id: "pinterest_marketing", label: "Pinterest Marketing" },
  { id: "twitter_x_marketing", label: "X (Twitter) Growth & Community" },
  { id: "reputation_management", label: "Online Reputation & Review Management" },
  { id: "ab_testing", label: "A/B Testing & Ad Optimization" },
  { id: "crm_integration", label: "HubSpot / CRM Marketing Automation" },
  { id: "viral_campaigns", label: "Viral Campaign Ideation" },
  { id: "video_marketing", label: "YouTube SEO & Channel Growth" },
];

