export const webDevelopmentSkills = [
  { id: "html", label: "HTML" },
  { id: "css", label: "CSS" },
  { id: "javascript", label: "JavaScript" },
  { id: "react", label: "React" },
  { id: "nodejs", label: "Node.js" },
  { id: "typescript", label: "TypeScript" },
  { id: "graphql", label: "GraphQL" },
  { id: "mongodb", label: "MongoDB" },
  { id: "express", label: "Express" },
  { id: "nextjs", label: "Next.js" },
  { id: "vue", label: "Vue.js" },
  { id: "git", label: "Git" },
  { id: "sass", label: "Sass" },
  { id: "webpack", label: "Webpack" },
  { id: "docker", label: "Docker" },
  { id: "ci_cd", label: "CI/CD" },
  { id: "aws", label: "AWS" },
  { id: "azure", label: "Azure" },
  { id: "firebase", label: "Firebase" },
];

export const appDevelopmentSkills = [
  { id: "java", label: "Java" },
  { id: "kotlin", label: "Kotlin" },
  { id: "swift", label: "Swift" },
  { id: "objective_c", label: "Objective-C" },
  { id: "react_native", label: "React Native" },
  { id: "flutter", label: "Flutter" },
  { id: "dart", label: "Dart" },
  { id: "android_sdk", label: "Android SDK" },
  { id: "ios_sdk", label: "iOS SDK" },
  { id: "xcode", label: "Xcode" },
  { id: "gradle", label: "Gradle" },
  { id: "firebase", label: "Firebase" },
  { id: "graphql", label: "GraphQL" },
  { id: "git", label: "Git" },
  { id: "ci_cd", label: "CI/CD" },
];

export const graphicDesignSkills = [
  { id: "photoshop", label: "Adobe Photoshop" },
  { id: "illustrator", label: "Adobe Illustrator" },
  { id: "xd", label: "Adobe XD" },
  { id: "sketch", label: "Sketch" },
  { id: "figma", label: "Figma" },
  { id: "indesign", label: "Adobe InDesign" },
  { id: "coreldraw", label: "CorelDRAW" },
  { id: "after_effects", label: "Adobe After Effects" },
  { id: "cinema_4d", label: "Cinema 4D" },
  { id: "blender", label: "Blender" },
  { id: "invision", label: "InVision" },
  { id: "procreate", label: "Procreate" },
  { id: "web_design", label: "Web Design" },
  { id: "typography", label: "Typography" },
  { id: "branding", label: "Branding" },
];

export const consultingStrategySkills = [
  { id: "business_analysis", label: "Business Analysis" },
  { id: "strategic_planning", label: "Strategic Planning" },
  { id: "market_research", label: "Market Research" },
  { id: "project_management", label: "Project Management" },
  { id: "financial_analysis", label: "Financial Analysis" },
  { id: "data_analysis", label: "Data Analysis" },
  { id: "risk_management", label: "Risk Management" },
  { id: "change_management", label: "Change Management" },
  { id: "client_relationship", label: "Client Relationship Management" },
  { id: "presentation", label: "Presentation Skills" },
  { id: "communication", label: "Communication" },
  { id: "negotiation", label: "Negotiation" },
  { id: "problem_solving", label: "Problem-Solving" },
  { id: "leadership", label: "Leadership" },
];

export const contentWritingSkills = [
  { id: "copywriting", label: "Copywriting" },
  { id: "seo", label: "SEO" },
  { id: "content_strategy", label: "Content Strategy" },
  { id: "blog_writing", label: "Blog Writing" },
  { id: "technical_writing", label: "Technical Writing" },
  { id: "creative_writing", label: "Creative Writing" },
  { id: "proofreading", label: "Proofreading" },
  { id: "editing", label: "Editing" },
  { id: "social_media", label: "Social Media Content" },
  { id: "email_marketing", label: "Email Marketing" },
  { id: "content_management", label: "Content Management" },
  { id: "storytelling", label: "Storytelling" },
  { id: "press_releases", label: "Press Releases" },
  { id: "ghostwriting", label: "Ghostwriting" },
  { id: "research", label: "Research" },
];

export const softwareDevelopmentSkills = [
  { id: "c++", label: "C++" },
  { id: "java", label: "Java" },
  { id: "python", label: "Python" },
  { id: "csharp", label: "C#" },
  { id: "ruby", label: "Ruby" },
  { id: "golang", label: "Golang" },
  { id: "nodejs", label: "Node.js" },
  { id: "sql", label: "SQL" },
  { id: "no_sql", label: "NoSQL" },
  { id: "git", label: "Git" },
  { id: "docker", label: "Docker" },
  { id: "ci_cd", label: "CI/CD" },
  { id: "aws", label: "AWS" },
  { id: "azure", label: "Azure" },
  { id: "testing", label: "Testing/QA" },
];

export const videoProductionSkills = [
  { id: "videography", label: "Videography" },
  { id: "video_editing", label: "Video Editing" },
  { id: "adobe_premiere", label: "Adobe Premiere Pro" },
  { id: "final_cut_pro", label: "Final Cut Pro" },
  { id: "after_effects", label: "Adobe After Effects" },
  { id: "cinematography", label: "Cinematography" },
  { id: "storyboarding", label: "Storyboarding" },
  { id: "lighting", label: "Lighting" },
  { id: "color_grading", label: "Color Grading" },
  { id: "sound_design", label: "Sound Design" },
  { id: "motion_graphics", label: "Motion Graphics" },
  { id: "live_streaming", label: "Live Streaming" },
  { id: "drone_videography", label: "Drone Videography" },
  { id: "video_compression", label: "Video Compression" },
];

export const socialMediaMarketingSkills = [
  { id: "social_media_strategy", label: "Social Media Strategy" },
  { id: "content_creation", label: "Content Creation" },
  { id: "social_media_management", label: "Social Media Management" },
  { id: "analytics", label: "Analytics" },
  { id: "copywriting", label: "Copywriting" },
  { id: "advertising", label: "Advertising" },
  { id: "branding", label: "Branding" },
  { id: "community_management", label: "Community Management" },
  { id: "graphic_design", label: "Graphic Design" },
  { id: "video_production", label: "Video Production" },
  { id: "photography", label: "Photography" },
  { id: "seo", label: "SEO" },
  { id: "email_marketing", label: "Email Marketing" },
  { id: "customer_service", label: "Customer Service" },
  { id: "data_analysis", label: "Data Analysis" },
];
